// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoliFoodCaso.DAO;

#nullable disable

namespace PoliFoodCaso.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518170029_SeedOrdenes")]
    partial class SeedOrdenes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-0001-4000-8000-000000000001",
                            ConcurrencyStamp = "a1b2c3d4-0001-4000-8000-000000000001",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "a1b2c3d4-0002-4000-8000-000000000002",
                            ConcurrencyStamp = "a1b2c3d4-0002-4000-8000-000000000002",
                            Name = "Vendor",
                            NormalizedName = "VENDOR"
                        },
                        new
                        {
                            Id = "a1b2c3d4-0003-4000-8000-000000000003",
                            ConcurrencyStamp = "a1b2c3d4-0003-4000-8000-000000000003",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b1b2c3d4-1001-4000-8000-000000000001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b1b2c3d4-1001-4000-8000-000000000001",
                            Email = "admin@polifood.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@POLIFOOD.EDU",
                            NormalizedUserName = "ADMIN@POLIFOOD.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAEEBWGNitMvuS+1Fw5Yby2cDtcrn7ZRJWCz1ZNei8DQ1UxMRtzahLv77X6zn5eY/3+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-stamp-admin1",
                            TwoFactorEnabled = false,
                            UserName = "admin@polifood.edu"
                        },
                        new
                        {
                            Id = "b1b2c3d4-2001-4000-8000-000000000002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b1b2c3d4-2001-4000-8000-000000000002",
                            Email = "burguer@polifood.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BURGUER@POLIFOOD.EDU",
                            NormalizedUserName = "BURGUER@POLIFOOD.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAEEBWGNitMvuS+1Fw5Yby2cDtcrn7ZRJWCz1ZNei8DQ1UxMRtzahLv77X6zn5eY/3+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-stamp-vendor1",
                            TwoFactorEnabled = false,
                            UserName = "burguer@polifood.edu"
                        },
                        new
                        {
                            Id = "b1b2c3d4-2002-4000-8000-000000000003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b1b2c3d4-2002-4000-8000-000000000003",
                            Email = "pizza@polifood.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PIZZA@POLIFOOD.EDU",
                            NormalizedUserName = "PIZZA@POLIFOOD.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAEEBWGNitMvuS+1Fw5Yby2cDtcrn7ZRJWCz1ZNei8DQ1UxMRtzahLv77X6zn5eY/3+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-stamp-vendor2",
                            TwoFactorEnabled = false,
                            UserName = "pizza@polifood.edu"
                        },
                        new
                        {
                            Id = "b1b2c3d4-3001-4000-8000-000000000004",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b1b2c3d4-3001-4000-8000-000000000004",
                            Email = "estudiante@polifood.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ESTUDIANTE@POLIFOOD.EDU",
                            NormalizedUserName = "ESTUDIANTE@POLIFOOD.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAEEBWGNitMvuS+1Fw5Yby2cDtcrn7ZRJWCz1ZNei8DQ1UxMRtzahLv77X6zn5eY/3+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-stamp-student1",
                            TwoFactorEnabled = false,
                            UserName = "estudiante@polifood.edu"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b1b2c3d4-1001-4000-8000-000000000001",
                            RoleId = "a1b2c3d4-0001-4000-8000-000000000001"
                        },
                        new
                        {
                            UserId = "b1b2c3d4-2001-4000-8000-000000000002",
                            RoleId = "a1b2c3d4-0002-4000-8000-000000000002"
                        },
                        new
                        {
                            UserId = "b1b2c3d4-2002-4000-8000-000000000003",
                            RoleId = "a1b2c3d4-0002-4000-8000-000000000002"
                        },
                        new
                        {
                            UserId = "b1b2c3d4-3001-4000-8000-000000000004",
                            RoleId = "a1b2c3d4-0003-4000-8000-000000000003"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PoliFoodCaso.Models.CarritoItem", b =>
                {
                    b.Property<Guid>("id_carrito_item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("productoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("studentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_carrito_item");

                    b.HasIndex("productoId");

                    b.ToTable("CarritoItem");
                });

            modelBuilder.Entity("PoliFoodCaso.Models.Categoria", b =>
                {
                    b.Property<Guid>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("isActive")
                        .HasColumnType("int");

                    b.Property<string>("nombre_categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("tiendaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id_categoria");

                    b.HasIndex("tiendaId");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            id_categoria = new Guid("d1b2c3d4-5001-4000-8000-000000000007"),
                            isActive = 1,
                            nombre_categoria = "Hamburguesas",
                            tiendaId = new Guid("c1b2c3d4-4001-4000-8000-000000000005")
                        },
                        new
                        {
                            id_categoria = new Guid("d1b2c3d4-5002-4000-8000-000000000008"),
                            isActive = 1,
                            nombre_categoria = "Bebidas",
                            tiendaId = new Guid("c1b2c3d4-4001-4000-8000-000000000005")
                        },
                        new
                        {
                            id_categoria = new Guid("d1b2c3d4-5003-4000-8000-000000000009"),
                            isActive = 1,
                            nombre_categoria = "Pizzas",
                            tiendaId = new Guid("c1b2c3d4-4002-4000-8000-000000000006")
                        },
                        new
                        {
                            id_categoria = new Guid("d1b2c3d4-5004-4000-8000-000000000010"),
                            isActive = 1,
                            nombre_categoria = "Postres",
                            tiendaId = new Guid("c1b2c3d4-4002-4000-8000-000000000006")
                        });
                });

            modelBuilder.Entity("PoliFoodCaso.Models.Orden", b =>
                {
                    b.Property<Guid>("id_orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("fecha_pago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("isActive")
                        .HasColumnType("int");

                    b.Property<int>("minutos_estimados")
                        .HasColumnType("int");

                    b.Property<bool>("pago_confirmado")
                        .HasColumnType("bit");

                    b.Property<string>("studentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("tiendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("total")
                        .HasColumnType("float");

                    b.HasKey("id_orden");

                    b.HasIndex("tiendaId");

                    b.ToTable("Orden");

                    b.HasData(
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7001-4000-8000-000000000023"),
                            estado = 0,
                            fecha_creacion = new DateTime(2026, 5, 2, 13, 30, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T13:31:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 12,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4001-4000-8000-000000000005"),
                            total = 19500.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7002-4000-8000-000000000024"),
                            estado = 0,
                            fecha_creacion = new DateTime(2026, 5, 2, 13, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T13:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 17,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4001-4000-8000-000000000005"),
                            total = 18500.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7003-4000-8000-000000000025"),
                            estado = 1,
                            fecha_creacion = new DateTime(2026, 5, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T12:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 13,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4001-4000-8000-000000000005"),
                            total = 20000.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7004-4000-8000-000000000026"),
                            estado = 1,
                            fecha_creacion = new DateTime(2026, 5, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T11:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 26,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4001-4000-8000-000000000005"),
                            total = 35000.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7005-4000-8000-000000000027"),
                            estado = 2,
                            fecha_creacion = new DateTime(2026, 5, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T09:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 22,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4001-4000-8000-000000000005"),
                            total = 32000.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7006-4000-8000-000000000028"),
                            estado = 2,
                            fecha_creacion = new DateTime(2026, 5, 2, 7, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T07:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 17,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4001-4000-8000-000000000005"),
                            total = 18500.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7007-4000-8000-000000000029"),
                            estado = 3,
                            fecha_creacion = new DateTime(2026, 5, 2, 2, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T02:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 25,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4001-4000-8000-000000000005"),
                            total = 36500.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7008-4000-8000-000000000030"),
                            estado = 3,
                            fecha_creacion = new DateTime(2026, 5, 1, 20, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-01T20:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 13,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4001-4000-8000-000000000005"),
                            total = 17500.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7009-4000-8000-000000000031"),
                            estado = 3,
                            fecha_creacion = new DateTime(2026, 5, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-01T14:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 33,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4001-4000-8000-000000000005"),
                            total = 48000.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7010-4000-8000-000000000032"),
                            estado = 3,
                            fecha_creacion = new DateTime(2026, 5, 1, 2, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-01T02:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 34,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4001-4000-8000-000000000005"),
                            total = 37000.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7011-4000-8000-000000000033"),
                            estado = 0,
                            fecha_creacion = new DateTime(2026, 5, 2, 13, 45, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T13:46:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 17,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4002-4000-8000-000000000006"),
                            total = 25000.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7012-4000-8000-000000000034"),
                            estado = 0,
                            fecha_creacion = new DateTime(2026, 5, 2, 13, 15, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T13:16:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 20,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4002-4000-8000-000000000006"),
                            total = 30000.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7013-4000-8000-000000000035"),
                            estado = 1,
                            fecha_creacion = new DateTime(2026, 5, 2, 12, 30, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T12:31:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 24,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4002-4000-8000-000000000006"),
                            total = 39000.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7014-4000-8000-000000000036"),
                            estado = 1,
                            fecha_creacion = new DateTime(2026, 5, 2, 11, 30, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T11:31:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 32,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4002-4000-8000-000000000006"),
                            total = 44000.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7015-4000-8000-000000000037"),
                            estado = 1,
                            fecha_creacion = new DateTime(2026, 5, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T10:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 22,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4002-4000-8000-000000000006"),
                            total = 38000.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7016-4000-8000-000000000038"),
                            estado = 2,
                            fecha_creacion = new DateTime(2026, 5, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T08:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 22,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4002-4000-8000-000000000006"),
                            total = 32000.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7017-4000-8000-000000000039"),
                            estado = 2,
                            fecha_creacion = new DateTime(2026, 5, 2, 6, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T06:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 17,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4002-4000-8000-000000000006"),
                            total = 26000.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7018-4000-8000-000000000040"),
                            estado = 3,
                            fecha_creacion = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-02T00:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 38,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4002-4000-8000-000000000006"),
                            total = 51000.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7019-4000-8000-000000000041"),
                            estado = 3,
                            fecha_creacion = new DateTime(2026, 5, 1, 18, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-01T18:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 22,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4002-4000-8000-000000000006"),
                            total = 33000.0
                        },
                        new
                        {
                            id_orden = new Guid("f1b2c3d4-7020-4000-8000-000000000042"),
                            estado = 3,
                            fecha_creacion = new DateTime(2026, 5, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            fecha_pago = "2026-05-01T06:01:00.0000000Z",
                            isActive = 1,
                            minutos_estimados = 17,
                            pago_confirmado = true,
                            studentId = "b1b2c3d4-3001-4000-8000-000000000004",
                            tiendaId = new Guid("c1b2c3d4-4002-4000-8000-000000000006"),
                            total = 25000.0
                        });
                });

            modelBuilder.Entity("PoliFoodCaso.Models.OrdenItem", b =>
                {
                    b.Property<Guid>("id_orden_item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("ordenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("precio_unitario")
                        .HasColumnType("float");

                    b.Property<Guid>("productoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id_orden_item");

                    b.HasIndex("ordenId");

                    b.HasIndex("productoId");

                    b.ToTable("OrdenItem");

                    b.HasData(
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8001-4000-8000-000000000043"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7001-4000-8000-000000000023"),
                            precio_unitario = 12500.0,
                            productoId = new Guid("e1b2c3d4-6001-4000-8000-000000000011")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8002-4000-8000-000000000044"),
                            cantidad = 2,
                            ordenId = new Guid("f1b2c3d4-7001-4000-8000-000000000023"),
                            precio_unitario = 3500.0,
                            productoId = new Guid("e1b2c3d4-6005-4000-8000-000000000015")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8003-4000-8000-000000000045"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7002-4000-8000-000000000024"),
                            precio_unitario = 14000.0,
                            productoId = new Guid("e1b2c3d4-6003-4000-8000-000000000013")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8004-4000-8000-000000000046"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7002-4000-8000-000000000024"),
                            precio_unitario = 4500.0,
                            productoId = new Guid("e1b2c3d4-6006-4000-8000-000000000016")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8005-4000-8000-000000000047"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7003-4000-8000-000000000025"),
                            precio_unitario = 16500.0,
                            productoId = new Guid("e1b2c3d4-6002-4000-8000-000000000012")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8006-4000-8000-000000000048"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7003-4000-8000-000000000025"),
                            precio_unitario = 3500.0,
                            productoId = new Guid("e1b2c3d4-6005-4000-8000-000000000015")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8007-4000-8000-000000000049"),
                            cantidad = 2,
                            ordenId = new Guid("f1b2c3d4-7004-4000-8000-000000000026"),
                            precio_unitario = 13000.0,
                            productoId = new Guid("e1b2c3d4-6004-4000-8000-000000000014")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8008-4000-8000-000000000050"),
                            cantidad = 2,
                            ordenId = new Guid("f1b2c3d4-7004-4000-8000-000000000026"),
                            precio_unitario = 4500.0,
                            productoId = new Guid("e1b2c3d4-6006-4000-8000-000000000016")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8009-4000-8000-000000000051"),
                            cantidad = 2,
                            ordenId = new Guid("f1b2c3d4-7005-4000-8000-000000000027"),
                            precio_unitario = 12500.0,
                            productoId = new Guid("e1b2c3d4-6001-4000-8000-000000000011")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8010-4000-8000-000000000052"),
                            cantidad = 2,
                            ordenId = new Guid("f1b2c3d4-7005-4000-8000-000000000027"),
                            precio_unitario = 3500.0,
                            productoId = new Guid("e1b2c3d4-6005-4000-8000-000000000015")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8011-4000-8000-000000000053"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7006-4000-8000-000000000028"),
                            precio_unitario = 14000.0,
                            productoId = new Guid("e1b2c3d4-6003-4000-8000-000000000013")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8012-4000-8000-000000000054"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7006-4000-8000-000000000028"),
                            precio_unitario = 4500.0,
                            productoId = new Guid("e1b2c3d4-6006-4000-8000-000000000016")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8013-4000-8000-000000000055"),
                            cantidad = 2,
                            ordenId = new Guid("f1b2c3d4-7007-4000-8000-000000000029"),
                            precio_unitario = 16500.0,
                            productoId = new Guid("e1b2c3d4-6002-4000-8000-000000000012")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8014-4000-8000-000000000056"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7007-4000-8000-000000000029"),
                            precio_unitario = 3500.0,
                            productoId = new Guid("e1b2c3d4-6005-4000-8000-000000000015")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8015-4000-8000-000000000057"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7008-4000-8000-000000000030"),
                            precio_unitario = 13000.0,
                            productoId = new Guid("e1b2c3d4-6004-4000-8000-000000000014")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8016-4000-8000-000000000058"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7008-4000-8000-000000000030"),
                            precio_unitario = 4500.0,
                            productoId = new Guid("e1b2c3d4-6006-4000-8000-000000000016")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8017-4000-8000-000000000059"),
                            cantidad = 3,
                            ordenId = new Guid("f1b2c3d4-7009-4000-8000-000000000031"),
                            precio_unitario = 12500.0,
                            productoId = new Guid("e1b2c3d4-6001-4000-8000-000000000011")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8018-4000-8000-000000000060"),
                            cantidad = 3,
                            ordenId = new Guid("f1b2c3d4-7009-4000-8000-000000000031"),
                            precio_unitario = 3500.0,
                            productoId = new Guid("e1b2c3d4-6005-4000-8000-000000000015")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8019-4000-8000-000000000061"),
                            cantidad = 2,
                            ordenId = new Guid("f1b2c3d4-7010-4000-8000-000000000032"),
                            precio_unitario = 14000.0,
                            productoId = new Guid("e1b2c3d4-6003-4000-8000-000000000013")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8020-4000-8000-000000000062"),
                            cantidad = 2,
                            ordenId = new Guid("f1b2c3d4-7010-4000-8000-000000000032"),
                            precio_unitario = 4500.0,
                            productoId = new Guid("e1b2c3d4-6006-4000-8000-000000000016")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8021-4000-8000-000000000063"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7011-4000-8000-000000000033"),
                            precio_unitario = 18000.0,
                            productoId = new Guid("e1b2c3d4-6007-4000-8000-000000000017")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8022-4000-8000-000000000064"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7011-4000-8000-000000000033"),
                            precio_unitario = 7000.0,
                            productoId = new Guid("e1b2c3d4-6012-4000-8000-000000000022")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8023-4000-8000-000000000065"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7012-4000-8000-000000000034"),
                            precio_unitario = 22000.0,
                            productoId = new Guid("e1b2c3d4-6008-4000-8000-000000000018")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8024-4000-8000-000000000066"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7012-4000-8000-000000000034"),
                            precio_unitario = 8000.0,
                            productoId = new Guid("e1b2c3d4-6011-4000-8000-000000000021")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8025-4000-8000-000000000067"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7013-4000-8000-000000000035"),
                            precio_unitario = 25000.0,
                            productoId = new Guid("e1b2c3d4-6009-4000-8000-000000000019")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8026-4000-8000-000000000068"),
                            cantidad = 2,
                            ordenId = new Guid("f1b2c3d4-7013-4000-8000-000000000035"),
                            precio_unitario = 7000.0,
                            productoId = new Guid("e1b2c3d4-6012-4000-8000-000000000022")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8027-4000-8000-000000000069"),
                            cantidad = 2,
                            ordenId = new Guid("f1b2c3d4-7014-4000-8000-000000000036"),
                            precio_unitario = 18000.0,
                            productoId = new Guid("e1b2c3d4-6007-4000-8000-000000000017")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8028-4000-8000-000000000070"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7014-4000-8000-000000000036"),
                            precio_unitario = 8000.0,
                            productoId = new Guid("e1b2c3d4-6011-4000-8000-000000000021")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8029-4000-8000-000000000071"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7015-4000-8000-000000000037"),
                            precio_unitario = 22000.0,
                            productoId = new Guid("e1b2c3d4-6008-4000-8000-000000000018")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8030-4000-8000-000000000072"),
                            cantidad = 2,
                            ordenId = new Guid("f1b2c3d4-7015-4000-8000-000000000037"),
                            precio_unitario = 8000.0,
                            productoId = new Guid("e1b2c3d4-6011-4000-8000-000000000021")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8031-4000-8000-000000000073"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7016-4000-8000-000000000038"),
                            precio_unitario = 25000.0,
                            productoId = new Guid("e1b2c3d4-6009-4000-8000-000000000019")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8032-4000-8000-000000000074"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7016-4000-8000-000000000038"),
                            precio_unitario = 7000.0,
                            productoId = new Guid("e1b2c3d4-6012-4000-8000-000000000022")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8033-4000-8000-000000000075"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7017-4000-8000-000000000039"),
                            precio_unitario = 18000.0,
                            productoId = new Guid("e1b2c3d4-6007-4000-8000-000000000017")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8034-4000-8000-000000000076"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7017-4000-8000-000000000039"),
                            precio_unitario = 8000.0,
                            productoId = new Guid("e1b2c3d4-6011-4000-8000-000000000021")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8035-4000-8000-000000000077"),
                            cantidad = 2,
                            ordenId = new Guid("f1b2c3d4-7018-4000-8000-000000000040"),
                            precio_unitario = 22000.0,
                            productoId = new Guid("e1b2c3d4-6008-4000-8000-000000000018")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8036-4000-8000-000000000078"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7018-4000-8000-000000000040"),
                            precio_unitario = 7000.0,
                            productoId = new Guid("e1b2c3d4-6012-4000-8000-000000000022")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8037-4000-8000-000000000079"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7019-4000-8000-000000000041"),
                            precio_unitario = 25000.0,
                            productoId = new Guid("e1b2c3d4-6009-4000-8000-000000000019")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8038-4000-8000-000000000080"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7019-4000-8000-000000000041"),
                            precio_unitario = 8000.0,
                            productoId = new Guid("e1b2c3d4-6011-4000-8000-000000000021")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8039-4000-8000-000000000081"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7020-4000-8000-000000000042"),
                            precio_unitario = 18000.0,
                            productoId = new Guid("e1b2c3d4-6007-4000-8000-000000000017")
                        },
                        new
                        {
                            id_orden_item = new Guid("f1b2c3d4-8040-4000-8000-000000000082"),
                            cantidad = 1,
                            ordenId = new Guid("f1b2c3d4-7020-4000-8000-000000000042"),
                            precio_unitario = 7000.0,
                            productoId = new Guid("e1b2c3d4-6012-4000-8000-000000000022")
                        });
                });

            modelBuilder.Entity("PoliFoodCaso.Models.Producto", b =>
                {
                    b.Property<Guid>("id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("categoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("disponible")
                        .HasColumnType("bit");

                    b.Property<string>("imagen_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("isActive")
                        .HasColumnType("int");

                    b.Property<int>("minutos_preparacion")
                        .HasColumnType("int");

                    b.Property<string>("nombre_producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precio")
                        .HasColumnType("float");

                    b.HasKey("id_producto");

                    b.HasIndex("categoriaId");

                    b.ToTable("Producto");

                    b.HasData(
                        new
                        {
                            id_producto = new Guid("e1b2c3d4-6001-4000-8000-000000000011"),
                            categoriaId = new Guid("d1b2c3d4-5001-4000-8000-000000000007"),
                            descripcion = "Carne 150g, lechuga, tomate, queso",
                            disponible = true,
                            imagen_url = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300",
                            isActive = 1,
                            minutos_preparacion = 10,
                            nombre_producto = "Clásica",
                            precio = 12500.0
                        },
                        new
                        {
                            id_producto = new Guid("e1b2c3d4-6002-4000-8000-000000000012"),
                            categoriaId = new Guid("d1b2c3d4-5001-4000-8000-000000000007"),
                            descripcion = "Doble carne, doble queso cheddar",
                            disponible = true,
                            imagen_url = "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=300",
                            isActive = 1,
                            minutos_preparacion = 12,
                            nombre_producto = "Doble Cheddar",
                            precio = 16500.0
                        },
                        new
                        {
                            id_producto = new Guid("e1b2c3d4-6003-4000-8000-000000000013"),
                            categoriaId = new Guid("d1b2c3d4-5001-4000-8000-000000000007"),
                            descripcion = "Pechuga apanada, mayonesa especial",
                            disponible = true,
                            imagen_url = "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=300",
                            isActive = 1,
                            minutos_preparacion = 14,
                            nombre_producto = "Pollo Crispy",
                            precio = 14000.0
                        },
                        new
                        {
                            id_producto = new Guid("e1b2c3d4-6004-4000-8000-000000000014"),
                            categoriaId = new Guid("d1b2c3d4-5001-4000-8000-000000000007"),
                            descripcion = "Hamburguesa de garbanzo vegana",
                            disponible = true,
                            imagen_url = "https://images.unsplash.com/photo-1520072959219-c595dc870360?w=300",
                            isActive = 1,
                            minutos_preparacion = 10,
                            nombre_producto = "Veggie",
                            precio = 13000.0
                        },
                        new
                        {
                            id_producto = new Guid("e1b2c3d4-6005-4000-8000-000000000015"),
                            categoriaId = new Guid("d1b2c3d4-5002-4000-8000-000000000008"),
                            descripcion = "350ml fría",
                            disponible = true,
                            imagen_url = "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=300",
                            isActive = 1,
                            minutos_preparacion = 1,
                            nombre_producto = "Gaseosa",
                            precio = 3500.0
                        },
                        new
                        {
                            id_producto = new Guid("e1b2c3d4-6006-4000-8000-000000000016"),
                            categoriaId = new Guid("d1b2c3d4-5002-4000-8000-000000000008"),
                            descripcion = "Limón, agua, azúcar, hielo",
                            disponible = true,
                            imagen_url = "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=300",
                            isActive = 1,
                            minutos_preparacion = 3,
                            nombre_producto = "Limonada",
                            precio = 4500.0
                        },
                        new
                        {
                            id_producto = new Guid("e1b2c3d4-6007-4000-8000-000000000017"),
                            categoriaId = new Guid("d1b2c3d4-5003-4000-8000-000000000009"),
                            descripcion = "Salsa, mozzarella y albahaca",
                            disponible = true,
                            imagen_url = "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=300",
                            isActive = 1,
                            minutos_preparacion = 15,
                            nombre_producto = "Margarita",
                            precio = 18000.0
                        },
                        new
                        {
                            id_producto = new Guid("e1b2c3d4-6008-4000-8000-000000000018"),
                            categoriaId = new Guid("d1b2c3d4-5003-4000-8000-000000000009"),
                            descripcion = "Salsa, pepperoni y mozzarella",
                            disponible = true,
                            imagen_url = "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=300",
                            isActive = 1,
                            minutos_preparacion = 18,
                            nombre_producto = "Pepperoni",
                            precio = 22000.0
                        },
                        new
                        {
                            id_producto = new Guid("e1b2c3d4-6009-4000-8000-000000000019"),
                            categoriaId = new Guid("d1b2c3d4-5003-4000-8000-000000000009"),
                            descripcion = "Mozzarella, cheddar, azul, parm",
                            disponible = true,
                            imagen_url = "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=300",
                            isActive = 1,
                            minutos_preparacion = 20,
                            nombre_producto = "4 Quesos",
                            precio = 25000.0
                        },
                        new
                        {
                            id_producto = new Guid("e1b2c3d4-6010-4000-8000-000000000020"),
                            categoriaId = new Guid("d1b2c3d4-5003-4000-8000-000000000009"),
                            descripcion = "Piña, jamón, mozzarella",
                            disponible = false,
                            imagen_url = "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=300",
                            isActive = 1,
                            minutos_preparacion = 18,
                            nombre_producto = "Hawaiana",
                            precio = 21000.0
                        },
                        new
                        {
                            id_producto = new Guid("e1b2c3d4-6011-4000-8000-000000000021"),
                            categoriaId = new Guid("d1b2c3d4-5004-4000-8000-000000000010"),
                            descripcion = "Porción individual artesanal",
                            disponible = true,
                            imagen_url = "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=300",
                            isActive = 1,
                            minutos_preparacion = 2,
                            nombre_producto = "Tiramisú",
                            precio = 8000.0
                        },
                        new
                        {
                            id_producto = new Guid("e1b2c3d4-6012-4000-8000-000000000022"),
                            categoriaId = new Guid("d1b2c3d4-5004-4000-8000-000000000010"),
                            descripcion = "Brownie de chocolate con helado",
                            disponible = true,
                            imagen_url = "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=300",
                            isActive = 1,
                            minutos_preparacion = 2,
                            nombre_producto = "Brownie",
                            precio = 7000.0
                        });
                });

            modelBuilder.Entity("PoliFoodCaso.Models.Tienda", b =>
                {
                    b.Property<Guid>("id_tienda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("isActive")
                        .HasColumnType("int");

                    b.Property<string>("nombre_tienda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vendorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_tienda");

                    b.ToTable("Tienda");

                    b.HasData(
                        new
                        {
                            id_tienda = new Guid("c1b2c3d4-4001-4000-8000-000000000005"),
                            isActive = 1,
                            nombre_tienda = "Burguer Campus",
                            vendorId = "b1b2c3d4-2001-4000-8000-000000000002"
                        },
                        new
                        {
                            id_tienda = new Guid("c1b2c3d4-4002-4000-8000-000000000006"),
                            isActive = 1,
                            nombre_tienda = "Pizza Poli",
                            vendorId = "b1b2c3d4-2002-4000-8000-000000000003"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoliFoodCaso.Models.CarritoItem", b =>
                {
                    b.HasOne("PoliFoodCaso.Models.Producto", "producto")
                        .WithMany()
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("producto");
                });

            modelBuilder.Entity("PoliFoodCaso.Models.Categoria", b =>
                {
                    b.HasOne("PoliFoodCaso.Models.Tienda", "tienda")
                        .WithMany()
                        .HasForeignKey("tiendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tienda");
                });

            modelBuilder.Entity("PoliFoodCaso.Models.Orden", b =>
                {
                    b.HasOne("PoliFoodCaso.Models.Tienda", "tienda")
                        .WithMany()
                        .HasForeignKey("tiendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tienda");
                });

            modelBuilder.Entity("PoliFoodCaso.Models.OrdenItem", b =>
                {
                    b.HasOne("PoliFoodCaso.Models.Orden", "orden")
                        .WithMany()
                        .HasForeignKey("ordenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PoliFoodCaso.Models.Producto", "producto")
                        .WithMany()
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("orden");

                    b.Navigation("producto");
                });

            modelBuilder.Entity("PoliFoodCaso.Models.Producto", b =>
                {
                    b.HasOne("PoliFoodCaso.Models.Categoria", "categoria")
                        .WithMany()
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
